import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import externalLinks from './external-links';

const sidebar: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  wiki: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'category',
      label: 'External Links',
      items: externalLinks,
    },
  ],
};

export default sidebar;
