import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebar: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  wiki: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'category',
      label: 'External Links',
      items: [
        {
          type: 'link',
          href: 'https://www.warwickartscentre.co.uk/our-venues/',
          label: 'Warwick Arts Centre - Venue Info',
        },
      ],
    },
  ],
};

export default sidebar;
